version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pg_task_container
    environment:
      POSTGRES_USER: task_admin
      POSTGRES_PASSWORD: task_admin
      POSTGRES_DB: task_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - '8080:8080'
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
